<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-B9HQEPC" failures="1" tests="6" name="Create New Book and reterive data after creating" time="2.406" errors="0" timestamp="2025-05-18T21:36:53 EEST">
  <testcase classname="testcases.books.TC01_CreateNewBook" name="verifyCreateNewBook_P" time="1.505"/>
  <testcase classname="testcases.books.TC02_GetBookById" name="verifyGetBookByIdAfterDeleting_P" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.Response.jsonPath()&amp;quot; because &amp;quot;this.response&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.jsonPath()" because "this.response" is null
at testcases.books.TC02_GetBookById.verifyGetBookByIdAfterDeleting_P(TC02_GetBookById.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1269)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- verifyGetBookByIdAfterDeleting_P -->
  <testcase classname="testcases.books.TC02_GetBookById" name="verifyGetBookById_P" time="0.125"/>
  <testcase classname="testcases.books.TC03_UpdateBook" name="verifyUpdateBook_P" time="0.129"/>
  <testcase classname="testcases.books.TC04_PartialUpdateBook" name="verifyPartialUpdateBook_P" time="0.09"/>
  <testcase classname="testcases.books.TC05_DeleteBook" name="verifyDeleteBook_P" time="0.011"/>
  <testcase classname="testcases.TestBase" name="@BeforeTest setUrl" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUrl -->
  <testcase classname="testcases.TestBase" name="@BeforeTest setUrl" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUrl -->
  <testcase classname="testcases.TestBase" name="@BeforeTest setUrl" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUrl -->
  <testcase classname="testcases.TestBase" name="@BeforeTest setUrl" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUrl -->
</testsuite> <!-- Create New Book and reterive data after creating -->
